### ISSUE TITLE
Add approval types filter

### ISSUE THREAD

**Issue by gferon** [boxdot/gerritbot-rs#14]
For each comment, Gerrit send the list of approvals of the current change.

By default, Gerrit only has Code-Review as a label (and Verified has been removed from the default install), so it would be nice if you can provide a list of approval types to transform into a message.

**Comment by boxdot** [comment]
Do we want a white- or a black list of such types?

**Comment by boxdot** [comment]
Now, I am implementing formatting of messages in an external Lua script, this can be done also in the same place.
