### ISSUE TITLE
Draft gerrit patches are empty.

### ISSUE THREAD

**Issue by nzjony** [boxdot/gerritbot-rs#59]
I have a draft gerrit patchset and I get a comment from someone, this currently shows:

Patch Set 4:

(1 comment)

And there is nothing after (1 comment).

The bot unfortunately doesn't have permissions to see the comment, but it would be good to get at least a link to the patchset so that I can click on it, log in, and view the comment.

**Comment by gferon** [comment]
This happens when the bot account running the bot and listening on gerrit events does not have permissions to view your draft. For now, you need to add the bot account as a reviewer of your change.
